name: release build for tag

on:
  workflow_dispatch:
    inputs:
      chain:
        description: 'Comma separated list of repositories in build chain'
        required: true
      workflow_file_name:
        description: 'The name of the workflow file to trigger'
        required: true
      tag_name:
        description: 'The name of the tag to use for triggering the workflow'
        required: true

jobs:
  trigger_next_build:
    # needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: none
    steps:
      # Set Up前にcheckout必要
    - uses: actions/checkout@v3

    - name: Set Up
      id: setup
      uses: ./.github/workflows

    - name: Trigger next repo build
      if: success()  # Only run this step if the build was successful
      run: |
        IFS=',' read -r -a CHAIN_ARRAY <<< "${{ github.event.inputs.chain }}"
        WORKFLOW_FILE_NAME=${{ github.event.inputs.workflow_file_name }}
        TAG_NAME=${{ github.event.inputs.tag_name }}
        CURRENT_REPO=$(echo "${{ github.repository }}" | cut -d'/' -f2)  # This will be 'maven_common'
        NEXT_REPO_NAME=""
        FOUND_CURRENT=false

        echo "Chain is ${CHAIN_ARRAY[@]}"

        for REPO in "${CHAIN_ARRAY[@]}"; do
          if [ "$FOUND_CURRENT" = true ]; then
            NEXT_REPO_NAME=$REPO
            break
          fi
          if [ "$REPO" = "$CURRENT_REPO" ]; then
            FOUND_CURRENT=true
          fi
        done
        if [ -n "$NEXT_REPO_NAME" ]; then
          echo "Triggering workflow in $NEXT_REPO_NAME with file $WORKFLOW_FILE_NAME and tag $TAG_NAME"
          echo https://api.github.com/repos/coding-sample/$NEXT_REPO_NAME/actions/workflows/$WORKFLOW_FILE_NAME/dispatches
          echo "${{ github.event.inputs.chain }}"
          curl -X POST \
              -H "Authorization: token ${{ secrets.PKG_READ_ETERNAL }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/coding-sample/$NEXT_REPO_NAME/actions/workflows/$WORKFLOW_FILE_NAME/dispatches \
              -d '{"ref": "'$TAG_NAME'", "inputs": {"chain": "${{ github.event.inputs.chain }}", "workflow_file_name": "'$WORKFLOW_FILE_NAME'", "tag_name": "'$TAG_NAME'"}}'
        fi
